### ISSUE TITLE
Completar página principal do projeto e incluir diagrama de implantação

### ISSUE THREAD

**Issue by alinebrito** [cefetmg-2022-psi-g2/QG-Frontend#2]
Sugestão para a entrega final (23/11):  Completar  o arquivo ``README`` do projeto, incluindo uma descrição geral do sistema, integrantes do grupo, link para a página wiki,  e tecnologias utilizadas (versões, linguagens de programação, etc).

Senti falta de uma descrição geral dos microsserviços também. A página wiki, por exemplo, não encontrei  o [diagrama](https://github.com/alinebrito/cefet-mg-psi/blob/main/labs/lab-arquitetura-fisica.md), mostrando a comunicação entre eles.

Após finalizar a tarefa, vocês podem encerrar esta issue.

**Comment by lebraga1** [comment]
Concluído.
